sudo: false
language: go
go:
- master
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go test -v -race ./...
  - gometalinter
